apiVersion: apps/v1
kind: Deployment
metadata:
  name: sites-services
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sites-services
  template:
    metadata:
      labels:
        app: sites-services
    spec:
      containers:
        - name: sites-services
          image: sites_services:latest
          ports:
            - containerPort: 8080
