apiVersion: v1
kind: Service
metadata:
  name: sites-services
spec:
  type: NodePort
  selector:
    app: sites-services
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30003
