apiVersion: v1
kind: Service
metadata:
  name: distances-services
spec:
  type: NodePort
  selector:
    app: distances-services
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30002
