apiVersion: apps/v1
kind: Deployment
metadata:
  name: distances-services
spec:
  replicas: 1
  selector:
    matchLabels:
      app: distances-services
  template:
    metadata:
      labels:
        app: distances-services
    spec:
      containers:
        - name: distances-services
          image: distances_services:latest
          ports:
            - containerPort: 8080
