apiVersion: v1
kind: Service
metadata:
  name: calendar-services
spec:
  type: NodePort
  selector:
    app: calendar-services
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30001
