# Utiliser une image Java officielle comme base
FROM openjdk:19-jdk-alpine

# Définir le répertoire de travail
WORKDIR /app

# Copier le fichier JAR généré dans l'image
COPY target/calendar_services-0.0.1-SNAPSHOT.jar /app/calendar_services.jar

# Exposer le port sur lequel l'application va tourner
EXPOSE 8080

# Définir la commande pour exécuter l'application
ENTRYPOINT ["java", "-jar", "/app/calendar_services.jar"]
